//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;

import com.farm.R.id;
import com.farm.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AddPlantObservationRecord_
    extends AddPlantObservationRecord
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.addplantobservationrecord);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AddPlantObservationRecord_.IntentBuilder_ intent(Context context) {
        return new AddPlantObservationRecord_.IntentBuilder_(context);
    }

    public static AddPlantObservationRecord_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AddPlantObservationRecord_.IntentBuilder_(fragment);
    }

    public static AddPlantObservationRecord_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AddPlantObservationRecord_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btn_upload = ((Button) hasViews.findViewById(id.btn_upload));
        cb_plantType = ((CheckBox) hasViews.findViewById(id.cb_plantType));
        imgbtn_addpicture = ((ImageButton) hasViews.findViewById(id.imgbtn_addpicture));
        et_xNum = ((EditText) hasViews.findViewById(id.et_xNum));
        et_hNum = ((EditText) hasViews.findViewById(id.et_hNum));
        tv_zDate = ((TextView) hasViews.findViewById(id.tv_zDate));
        et_wNum = ((EditText) hasViews.findViewById(id.et_wNum));
        et_Ext1 = ((EditText) hasViews.findViewById(id.et_Ext1));
        tv_cDate = ((TextView) hasViews.findViewById(id.tv_cDate));
        tv_yNum = ((TextView) hasViews.findViewById(id.tv_yNum));
        tv_yColor = ((TextView) hasViews.findViewById(id.tv_yColor));
        ll_picture = ((LinearLayout) hasViews.findViewById(id.ll_picture));
        pb_upload = ((ProgressBar) hasViews.findViewById(id.pb_upload));
        tv_plantName = ((TextView) hasViews.findViewById(id.tv_plantName));
        if (imgbtn_addpicture!= null) {
            imgbtn_addpicture.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddPlantObservationRecord_.this.imgbtn_addpicture();
                }

            }
            );
        }
        if (tv_yNum!= null) {
            tv_yNum.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddPlantObservationRecord_.this.tv_yNum();
                }

            }
            );
        }
        if (tv_cDate!= null) {
            tv_cDate.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddPlantObservationRecord_.this.tv_cDate();
                }

            }
            );
        }
        if (btn_upload!= null) {
            btn_upload.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddPlantObservationRecord_.this.btn_upload();
                }

            }
            );
        }
        if (tv_yColor!= null) {
            tv_yColor.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddPlantObservationRecord_.this.tv_yColor();
                }

            }
            );
        }
        if (tv_zDate!= null) {
            tv_zDate.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddPlantObservationRecord_.this.tv_zDate();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<AddPlantObservationRecord_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, AddPlantObservationRecord_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), AddPlantObservationRecord_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), AddPlantObservationRecord_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
