//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioGroup;
import android.widget.TextView;

import com.farm.R.id;
import com.farm.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AddStandardCommand_
    extends AddStandardCommand
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.addcommand);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AddStandardCommand_.IntentBuilder_ intent(Context context) {
        return new AddStandardCommand_.IntentBuilder_(context);
    }

    public static AddStandardCommand_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AddStandardCommand_.IntentBuilder_(fragment);
    }

    public static AddStandardCommand_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AddStandardCommand_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_importance = ((TextView) hasViews.findViewById(id.tv_importance));
        tv_area = ((TextView) hasViews.findViewById(id.tv_area));
        btn_save = ((Button) hasViews.findViewById(id.btn_save));
        tv_timelimit = ((TextView) hasViews.findViewById(id.tv_timelimit));
        tv_workday = ((TextView) hasViews.findViewById(id.tv_workday));
        et_nz = ((EditText) hasViews.findViewById(id.et_nz));
        et_yl = ((EditText) hasViews.findViewById(id.et_yl));
        et_note = ((EditText) hasViews.findViewById(id.et_note));
        tv_selectcmd = ((TextView) hasViews.findViewById(id.tv_selectcmd));
        line = hasViews.findViewById(id.line);
        rg_level = ((RadioGroup) hasViews.findViewById(id.rg_level));
        if (tv_area!= null) {
            tv_area.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddStandardCommand_.this.tv_area();
                }

            }
            );
        }
        if (btn_save!= null) {
            btn_save.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddStandardCommand_.this.btn_save();
                }

            }
            );
        }
        if (tv_workday!= null) {
            tv_workday.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddStandardCommand_.this.tv_workday();
                }

            }
            );
        }
        if (tv_timelimit!= null) {
            tv_timelimit.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddStandardCommand_.this.tv_timelimit();
                }

            }
            );
        }
        if (tv_importance!= null) {
            tv_importance.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddStandardCommand_.this.tv_importance();
                }

            }
            );
        }
        if (tv_selectcmd!= null) {
            tv_selectcmd.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AddStandardCommand_.this.tv_selectcmd();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<AddStandardCommand_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, AddStandardCommand_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), AddStandardCommand_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), AddStandardCommand_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
