//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AudioFragment_
    extends com.farm.ui.AudioFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AudioFragment_.FragmentBuilder_ builder() {
        return new AudioFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btn_play = ((Button) hasViews.findViewById(com.farm.R.id.btn_play));
        btn_start = ((Button) hasViews.findViewById(com.farm.R.id.btn_start));
        if (btn_play!= null) {
            btn_play.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AudioFragment_.this.btn_play();
                }

            }
            );
        }
        if (btn_start!= null) {
            btn_start.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AudioFragment_.this.btn_start();
                }

            }
            );
        }
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<AudioFragment_.FragmentBuilder_, com.farm.ui.AudioFragment>
    {


        @Override
        public com.farm.ui.AudioFragment build() {
            AudioFragment_ fragment_ = new AudioFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
