//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.farm.widget.PullToRefreshListView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Common_TodayJob_
    extends com.farm.ui.Common_TodayJob
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static Common_TodayJob_.FragmentBuilder_ builder() {
        return new Common_TodayJob_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_more = ((TextView) hasViews.findViewById(com.farm.R.id.tv_more));
        tv_cmdnumber_new = ((TextView) hasViews.findViewById(com.farm.R.id.tv_cmdnumber_new));
        frame_listview_news = ((PullToRefreshListView) hasViews.findViewById(com.farm.R.id.frame_listview_news));
        fl_cmdnumber_new = ((FrameLayout) hasViews.findViewById(com.farm.R.id.fl_cmdnumber_new));
        btn_cmd = ((Button) hasViews.findViewById(com.farm.R.id.btn_cmd));
        btn_nature = ((Button) hasViews.findViewById(com.farm.R.id.btn_nature));
        tv_worknumber = ((TextView) hasViews.findViewById(com.farm.R.id.tv_worknumber));
        ll_tip = ((LinearLayout) hasViews.findViewById(com.farm.R.id.ll_tip));
        if (tv_more!= null) {
            tv_more.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Common_TodayJob_.this.tv_more();
                }

            }
            );
        }
        if (btn_cmd!= null) {
            btn_cmd.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Common_TodayJob_.this.btn_cmd();
                }

            }
            );
        }
        if (btn_nature!= null) {
            btn_nature.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Common_TodayJob_.this.btn_nature();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<Common_TodayJob_.FragmentBuilder_, com.farm.ui.Common_TodayJob>
    {


        @Override
        public com.farm.ui.Common_TodayJob build() {
            Common_TodayJob_ fragment_ = new Common_TodayJob_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
