//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;

import com.farm.R.id;
import com.farm.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Common_AddSpontaneityWork_
    extends Common_AddSpontaneityWork
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.addspontaneitywork);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static Common_AddSpontaneityWork_.IntentBuilder_ intent(Context context) {
        return new Common_AddSpontaneityWork_.IntentBuilder_(context);
    }

    public static Common_AddSpontaneityWork_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new Common_AddSpontaneityWork_.IntentBuilder_(fragment);
    }

    public static Common_AddSpontaneityWork_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new Common_AddSpontaneityWork_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        et_jobname = ((EditText) hasViews.findViewById(id.et_jobname));
        et_jobnote = ((EditText) hasViews.findViewById(id.et_jobnote));
        btn_save = ((Button) hasViews.findViewById(id.btn_save));
        {
            View view = hasViews.findViewById(id.btn_addtowork);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Common_AddSpontaneityWork_.this.btn_addtowork();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.tv_selectcmd);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Common_AddSpontaneityWork_.this.tv_selectcmd();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.tv_workday);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Common_AddSpontaneityWork_.this.tv_workday();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.tv_area);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Common_AddSpontaneityWork_.this.tv_area();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.tv_timelimit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Common_AddSpontaneityWork_.this.tv_timelimit();
                    }

                }
                );
            }
        }
        if (btn_save!= null) {
            btn_save.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Common_AddSpontaneityWork_.this.btn_save();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<Common_AddSpontaneityWork_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, Common_AddSpontaneityWork_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), Common_AddSpontaneityWork_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), Common_AddSpontaneityWork_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
