//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;

import com.farm.R.id;
import com.farm.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class CZ_ChangeWeather_
    extends CZ_ChangeWeather
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.pg_changeweather);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CZ_ChangeWeather_.IntentBuilder_ intent(Context context) {
        return new CZ_ChangeWeather_.IntentBuilder_(context);
    }

    public static CZ_ChangeWeather_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new CZ_ChangeWeather_.IntentBuilder_(fragment);
    }

    public static CZ_ChangeWeather_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new CZ_ChangeWeather_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        et_tempH = ((EditText) hasViews.findViewById(id.et_tempH));
        et_tempL = ((EditText) hasViews.findViewById(id.et_tempL));
        et_weather = ((EditText) hasViews.findViewById(id.et_weather));
        et_tempM = ((EditText) hasViews.findViewById(id.et_tempM));
        btn_upload = ((Button) hasViews.findViewById(id.btn_upload));
        if (btn_upload!= null) {
            btn_upload.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    CZ_ChangeWeather_.this.btn_upload();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.imgbtn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        CZ_ChangeWeather_.this.imgbtn_back();
                    }

                }
                );
            }
        }
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<CZ_ChangeWeather_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, CZ_ChangeWeather_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), CZ_ChangeWeather_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), CZ_ChangeWeather_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
