//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.TextView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class CZ_MainFragment_
    extends com.farm.ui.CZ_MainFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CZ_MainFragment_.FragmentBuilder_ builder() {
        return new CZ_MainFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_cmdnumber = ((TextView) hasViews.findViewById(com.farm.R.id.tv_cmdnumber));
        tv_worknumber_new = ((TextView) hasViews.findViewById(com.farm.R.id.tv_worknumber_new));
        tv_title = ((TextView) hasViews.findViewById(com.farm.R.id.tv_title));
        tv_worknumber = ((TextView) hasViews.findViewById(com.farm.R.id.tv_worknumber));
        fl_cmdnumber_new = ((FrameLayout) hasViews.findViewById(com.farm.R.id.fl_cmdnumber_new));
        tv_day = ((TextView) hasViews.findViewById(com.farm.R.id.tv_day));
        tv_cmdnumber_new = ((TextView) hasViews.findViewById(com.farm.R.id.tv_cmdnumber_new));
        fl_plantnumber_new = ((FrameLayout) hasViews.findViewById(com.farm.R.id.fl_plantnumber_new));
        tv_plantnumber_new = ((TextView) hasViews.findViewById(com.farm.R.id.tv_plantnumber_new));
        tv_plantnumber = ((TextView) hasViews.findViewById(com.farm.R.id.tv_plantnumber));
        fl_worknumber_new = ((FrameLayout) hasViews.findViewById(com.farm.R.id.fl_worknumber_new));
        {
            View view = hasViews.findViewById(com.farm.R.id.tl_jrqp);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        CZ_MainFragment_.this.tl_jrqp();
                    }

                }
                );
            }
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<CZ_MainFragment_.FragmentBuilder_, com.farm.ui.CZ_MainFragment>
    {


        @Override
        public com.farm.ui.CZ_MainFragment build() {
            CZ_MainFragment_ fragment_ = new CZ_MainFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
