//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class DayWeatherFragment_
    extends com.farm.ui.DayWeatherFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static DayWeatherFragment_.FragmentBuilder_ builder() {
        return new DayWeatherFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_tip_weather = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tip_weather));
        pb_getweather = ((ProgressBar) hasViews.findViewById(com.farm.R.id.pb_getweather));
        tv_tip_tempL = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tip_tempL));
        tv_tip_from = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tip_from));
        tv_tempM = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tempM));
        tv_tempL = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tempL));
        tv_tempH = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tempH));
        tv_tip_tempH = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tip_tempH));
        tv_tip_tempM = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tip_tempM));
        img_weather = ((ImageView) hasViews.findViewById(com.farm.R.id.img_weather));
        ll_tip = ((LinearLayout) hasViews.findViewById(com.farm.R.id.ll_tip));
        tv_from = ((TextView) hasViews.findViewById(com.farm.R.id.tv_from));
        tv_weather = ((TextView) hasViews.findViewById(com.farm.R.id.tv_weather));
        rl_weather = ((RelativeLayout) hasViews.findViewById(com.farm.R.id.rl_weather));
        tv_tip_getweather = ((TextView) hasViews.findViewById(com.farm.R.id.tv_tip_getweather));
        if (rl_weather!= null) {
            rl_weather.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    DayWeatherFragment_.this.rl_weather();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<DayWeatherFragment_.FragmentBuilder_, com.farm.ui.DayWeatherFragment>
    {


        @Override
        public com.farm.ui.DayWeatherFragment build() {
            DayWeatherFragment_ fragment_ = new DayWeatherFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
