//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.farm.widget.CalendarView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HistoryWeatherFragment_
    extends com.farm.ui.HistoryWeatherFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HistoryWeatherFragment_.FragmentBuilder_ builder() {
        return new HistoryWeatherFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        layout_calendar = ((RelativeLayout) hasViews.findViewById(com.farm.R.id.layout_calendar));
        calendarCenter = ((TextView) hasViews.findViewById(com.farm.R.id.calendarCenter));
        calendarLeft = ((ImageButton) hasViews.findViewById(com.farm.R.id.calendarLeft));
        tv_wd = ((TextView) hasViews.findViewById(com.farm.R.id.tv_wd));
        tv_day = ((TextView) hasViews.findViewById(com.farm.R.id.tv_day));
        calendarRight = ((ImageButton) hasViews.findViewById(com.farm.R.id.calendarRight));
        calendar = ((CalendarView) hasViews.findViewById(com.farm.R.id.calendar));
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<HistoryWeatherFragment_.FragmentBuilder_, com.farm.ui.HistoryWeatherFragment>
    {


        @Override
        public com.farm.ui.HistoryWeatherFragment build() {
            HistoryWeatherFragment_ fragment_ = new HistoryWeatherFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
