//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.farm.widget.CircleImageView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class IFragment_
    extends com.farm.ui.IFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static IFragment_.FragmentBuilder_ builder() {
        return new IFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        fl_new = ((FrameLayout) hasViews.findViewById(com.farm.R.id.fl_new));
        circle_img = ((CircleImageView) hasViews.findViewById(com.farm.R.id.circle_img));
        tv_changepwd = ((TextView) hasViews.findViewById(com.farm.R.id.tv_changepwd));
        tv_exist = ((TextView) hasViews.findViewById(com.farm.R.id.tv_exist));
        ll_edituser = ((LinearLayout) hasViews.findViewById(com.farm.R.id.ll_edituser));
        if (ll_edituser!= null) {
            ll_edituser.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    IFragment_.this.ll_edituser();
                }

            }
            );
        }
        if (tv_changepwd!= null) {
            tv_changepwd.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    IFragment_.this.tv_changepwd();
                }

            }
            );
        }
        if (tv_exist!= null) {
            tv_exist.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    IFragment_.this.tv_exist();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(com.farm.R.id.tv_gy);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        IFragment_.this.tv_gy();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.farm.R.id.tv_share);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        IFragment_.this.tv_share();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.farm.R.id.tv_yj);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        IFragment_.this.tv_yj();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.farm.R.id.tv_renewversion);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        IFragment_.this.tv_renewversion();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.farm.R.id.tv_bz);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        IFragment_.this.tv_bz();
                    }

                }
                );
            }
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<IFragment_.FragmentBuilder_, com.farm.ui.IFragment>
    {


        @Override
        public com.farm.ui.IFragment build() {
            IFragment_ fragment_ = new IFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
