//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageButton;
import android.widget.LinearLayout;

import com.farm.R.id;
import com.farm.R.layout;
import com.farm.widget.PullToRefreshListView;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class NCZ_CZ_ToDayJob_
    extends NCZ_CZ_ToDayJob
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.ncz_cz_todayjob);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static NCZ_CZ_ToDayJob_.IntentBuilder_ intent(Context context) {
        return new NCZ_CZ_ToDayJob_.IntentBuilder_(context);
    }

    public static NCZ_CZ_ToDayJob_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new NCZ_CZ_ToDayJob_.IntentBuilder_(fragment);
    }

    public static NCZ_CZ_ToDayJob_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new NCZ_CZ_ToDayJob_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        imgbtn_back = ((ImageButton) hasViews.findViewById(id.imgbtn_back));
        ll_tip = ((LinearLayout) hasViews.findViewById(id.ll_tip));
        frame_listview_news = ((PullToRefreshListView) hasViews.findViewById(id.frame_listview_news));
        if (imgbtn_back!= null) {
            imgbtn_back.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_CZ_ToDayJob_.this.imgbtn_back();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.tv_more);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NCZ_CZ_ToDayJob_.this.tv_more();
                    }

                }
                );
            }
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<NCZ_CZ_ToDayJob_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, NCZ_CZ_ToDayJob_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), NCZ_CZ_ToDayJob_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), NCZ_CZ_ToDayJob_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
