//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import com.farm.widget.PullToRefreshListView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class NCZ_YQPQ_
    extends com.farm.ui.NCZ_YQPQ
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static NCZ_YQPQ_.FragmentBuilder_ builder() {
        return new NCZ_YQPQ_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ll_tip = ((LinearLayout) hasViews.findViewById(com.farm.R.id.ll_tip));
        frame_listview_news = ((PullToRefreshListView) hasViews.findViewById(com.farm.R.id.frame_listview_news));
        {
            View view = hasViews.findViewById(com.farm.R.id.btn_cmd);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NCZ_YQPQ_.this.btn_cmd();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.farm.R.id.btn_nature);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NCZ_YQPQ_.this.btn_nature();
                    }

                }
                );
            }
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<NCZ_YQPQ_.FragmentBuilder_, com.farm.ui.NCZ_YQPQ>
    {


        @Override
        public com.farm.ui.NCZ_YQPQ build() {
            NCZ_YQPQ_ fragment_ = new NCZ_YQPQ_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
