//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.farm.R.id;
import com.farm.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class NCZ_CZ_JobDetail_
    extends NCZ_CZ_JobDetail
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.ncz_cz_jobdetail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static NCZ_CZ_JobDetail_.IntentBuilder_ intent(Context context) {
        return new NCZ_CZ_JobDetail_.IntentBuilder_(context);
    }

    public static NCZ_CZ_JobDetail_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new NCZ_CZ_JobDetail_.IntentBuilder_(fragment);
    }

    public static NCZ_CZ_JobDetail_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new NCZ_CZ_JobDetail_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_importance = ((TextView) hasViews.findViewById(id.tv_importance));
        btn_back = ((ImageButton) hasViews.findViewById(id.btn_back));
        tv_note = ((TextView) hasViews.findViewById(id.tv_note));
        tv_jobname = ((TextView) hasViews.findViewById(id.tv_jobname));
        tv_nz = ((TextView) hasViews.findViewById(id.tv_nz));
        tv_qx = ((TextView) hasViews.findViewById(id.tv_qx));
        tv_scorenote = ((TextView) hasViews.findViewById(id.tv_scorenote));
        tv_yl = ((TextView) hasViews.findViewById(id.tv_yl));
        btn_score = ((TextView) hasViews.findViewById(id.btn_score));
        tv_tip_nz = ((TextView) hasViews.findViewById(id.tv_tip_nz));
        ll_more = ((LinearLayout) hasViews.findViewById(id.ll_more));
        tv_score = ((TextView) hasViews.findViewById(id.tv_score));
        tv_tip_yl = ((TextView) hasViews.findViewById(id.tv_tip_yl));
        if (btn_score!= null) {
            btn_score.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_CZ_JobDetail_.this.btn_score();
                }

            }
            );
        }
        if (btn_back!= null) {
            btn_back.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_CZ_JobDetail_.this.btn_back();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<NCZ_CZ_JobDetail_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, NCZ_CZ_JobDetail_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), NCZ_CZ_JobDetail_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), NCZ_CZ_JobDetail_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
