//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.TableLayout;
import android.widget.TextView;

import com.farm.R.id;
import com.farm.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class NCZ_MainActivity_
    extends NCZ_MainActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.ncz_activity);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static NCZ_MainActivity_.IntentBuilder_ intent(Context context) {
        return new NCZ_MainActivity_.IntentBuilder_(context);
    }

    public static NCZ_MainActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new NCZ_MainActivity_.IntentBuilder_(fragment);
    }

    public static NCZ_MainActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new NCZ_MainActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tl_sale = ((TableLayout) hasViews.findViewById(id.tl_sale));
        imgbtn_money = ((ImageButton) hasViews.findViewById(id.imgbtn_money));
        imgbtn_product = ((ImageButton) hasViews.findViewById(id.imgbtn_product));
        tv_product = ((TextView) hasViews.findViewById(id.tv_product));
        tl_me = ((TableLayout) hasViews.findViewById(id.tl_me));
        tv_new = ((TextView) hasViews.findViewById(id.tv_new));
        tv_me = ((TextView) hasViews.findViewById(id.tv_me));
        tl_product = ((TableLayout) hasViews.findViewById(id.tl_product));
        tl_home = ((TableLayout) hasViews.findViewById(id.tl_home));
        fl_new = ((FrameLayout) hasViews.findViewById(id.fl_new));
        tl_money = ((TableLayout) hasViews.findViewById(id.tl_money));
        tv_sale = ((TextView) hasViews.findViewById(id.tv_sale));
        tv_money = ((TextView) hasViews.findViewById(id.tv_money));
        imgbtn_me = ((ImageButton) hasViews.findViewById(id.imgbtn_me));
        imgbtn_home = ((ImageButton) hasViews.findViewById(id.imgbtn_home));
        imgbtn_sale = ((ImageButton) hasViews.findViewById(id.imgbtn_sale));
        tv_home = ((TextView) hasViews.findViewById(id.tv_home));
        if (tl_home!= null) {
            tl_home.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_MainActivity_.this.tl_home();
                }

            }
            );
        }
        if (tl_money!= null) {
            tl_money.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_MainActivity_.this.tl_money();
                }

            }
            );
        }
        if (tl_me!= null) {
            tl_me.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_MainActivity_.this.tl_me();
                }

            }
            );
        }
        if (tl_sale!= null) {
            tl_sale.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_MainActivity_.this.tl_sale();
                }

            }
            );
        }
        if (tl_product!= null) {
            tl_product.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_MainActivity_.this.tl_product();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<NCZ_MainActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, NCZ_MainActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), NCZ_MainActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), NCZ_MainActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
