//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ScrollView;
import android.widget.TextView;

import com.farm.widget.PullToRefreshListView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class NCZ_MainFragment_
    extends com.farm.ui.NCZ_MainFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static NCZ_MainFragment_.FragmentBuilder_ builder() {
        return new NCZ_MainFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btn_zg = ((Button) hasViews.findViewById(com.farm.R.id.btn_zg));
        tv_title = ((TextView) hasViews.findViewById(com.farm.R.id.tv_title));
        tv_day = ((TextView) hasViews.findViewById(com.farm.R.id.tv_day));
        frame_listview_news = ((PullToRefreshListView) hasViews.findViewById(com.farm.R.id.frame_listview_news));
        sl = ((ScrollView) hasViews.findViewById(com.farm.R.id.sl));
        if (btn_zg!= null) {
            btn_zg.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NCZ_MainFragment_.this.btn_zg();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<NCZ_MainFragment_.FragmentBuilder_, com.farm.ui.NCZ_MainFragment>
    {


        @Override
        public com.farm.ui.NCZ_MainFragment build() {
            NCZ_MainFragment_ fragment_ = new NCZ_MainFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
