//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageButton;
import android.widget.TableLayout;
import android.widget.TextView;

import com.farm.R.id;
import com.farm.R.layout;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PG_MainActivity_
    extends PG_MainActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_pg);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PG_MainActivity_.IntentBuilder_ intent(Context context) {
        return new PG_MainActivity_.IntentBuilder_(context);
    }

    public static PG_MainActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PG_MainActivity_.IntentBuilder_(fragment);
    }

    public static PG_MainActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PG_MainActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        imgbtn_plant = ((ImageButton) hasViews.findViewById(id.imgbtn_plant));
        imgbtn_home = ((ImageButton) hasViews.findViewById(id.imgbtn_home));
        tv_plant = ((TextView) hasViews.findViewById(id.tv_plant));
        tv_home = ((TextView) hasViews.findViewById(id.tv_home));
        tl_home = ((TableLayout) hasViews.findViewById(id.tl_home));
        tl_plant = ((TableLayout) hasViews.findViewById(id.tl_plant));
        imgbtn_me = ((ImageButton) hasViews.findViewById(id.imgbtn_me));
        tl_me = ((TableLayout) hasViews.findViewById(id.tl_me));
        tv_me = ((TextView) hasViews.findViewById(id.tv_me));
        if (tl_me!= null) {
            tl_me.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PG_MainActivity_.this.tl_me();
                }

            }
            );
        }
        if (tl_plant!= null) {
            tl_plant.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PG_MainActivity_.this.tl_plant();
                }

            }
            );
        }
        if (tl_home!= null) {
            tl_home.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PG_MainActivity_.this.tl_home();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<PG_MainActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, PG_MainActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), PG_MainActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), PG_MainActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
