//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;

import com.farm.widget.PullToRefreshListView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PG_TodayPlant_
    extends com.farm.ui.PG_TodayPlant
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PG_TodayPlant_.FragmentBuilder_ builder() {
        return new PG_TodayPlant_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btn_add = ((ImageButton) hasViews.findViewById(com.farm.R.id.btn_add));
        line = hasViews.findViewById(com.farm.R.id.line);
        frame_listview_news = ((PullToRefreshListView) hasViews.findViewById(com.farm.R.id.frame_listview_news));
        btn_search = ((ImageButton) hasViews.findViewById(com.farm.R.id.btn_search));
        tv_title = ((TextView) hasViews.findViewById(com.farm.R.id.tv_title));
        if (btn_add!= null) {
            btn_add.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PG_TodayPlant_.this.btn_add();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<PG_TodayPlant_.FragmentBuilder_, com.farm.ui.PG_TodayPlant>
    {


        @Override
        public com.farm.ui.PG_TodayPlant build() {
            PG_TodayPlant_ fragment_ = new PG_TodayPlant_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
