//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.annotation.SuppressLint;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.farm.widget.PullToRefreshListView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

@SuppressLint({
    "NewApi"
})
public final class SelectorFragment_
    extends com.farm.ui.SelectorFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SelectorFragment_.FragmentBuilder_ builder() {
        return new SelectorFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        hs_selected = ((HorizontalScrollView) hasViews.findViewById(com.farm.R.id.hs_selected));
        iv_up_selector = ((ImageView) hasViews.findViewById(com.farm.R.id.iv_up_selector));
        tv_recent = ((TextView) hasViews.findViewById(com.farm.R.id.tv_recent));
        rl_recent = ((RelativeLayout) hasViews.findViewById(com.farm.R.id.rl_recent));
        frame_listview_news = ((PullToRefreshListView) hasViews.findViewById(com.farm.R.id.frame_listview_news));
        iv_up_recent = ((ImageView) hasViews.findViewById(com.farm.R.id.iv_up_recent));
        rl_selector = ((RelativeLayout) hasViews.findViewById(com.farm.R.id.rl_selector));
        ll_selected = ((LinearLayout) hasViews.findViewById(com.farm.R.id.ll_selected));
        line = hasViews.findViewById(com.farm.R.id.line);
        if (rl_recent!= null) {
            rl_recent.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SelectorFragment_.this.rl_recent();
                }

            }
            );
        }
        if (rl_selector!= null) {
            rl_selector.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SelectorFragment_.this.rl_selector();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<SelectorFragment_.FragmentBuilder_, com.farm.ui.SelectorFragment>
    {


        @Override
        public com.farm.ui.SelectorFragment build() {
            SelectorFragment_ fragment_ = new SelectorFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
