//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SpeedFragment_
    extends com.farm.ui.SpeedFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SpeedFragment_.FragmentBuilder_ builder() {
        return new SpeedFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        hs_container = ((HorizontalScrollView) hasViews.findViewById(com.farm.R.id.hs_container));
        tv_startroles = ((TextView) hasViews.findViewById(com.farm.R.id.tv_startroles));
        ll_container = ((LinearLayout) hasViews.findViewById(com.farm.R.id.ll_container));
        iv_start = ((ImageView) hasViews.findViewById(com.farm.R.id.iv_start));
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<SpeedFragment_.FragmentBuilder_, com.farm.ui.SpeedFragment>
    {


        @Override
        public com.farm.ui.SpeedFragment build() {
            SpeedFragment_ fragment_ = new SpeedFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
