//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.farm.ui;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.farm.widget.CalendarView;

import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class TimeSeLectorFragment_
    extends com.farm.ui.TimeSeLectorFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static TimeSeLectorFragment_.FragmentBuilder_ builder() {
        return new TimeSeLectorFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        calendarLeft = ((ImageButton) hasViews.findViewById(com.farm.R.id.calendarLeft));
        calendar = ((CalendarView) hasViews.findViewById(com.farm.R.id.calendar));
        iv_dowm_tab = ((ImageView) hasViews.findViewById(com.farm.R.id.iv_dowm_tab));
        calendarRight = ((ImageButton) hasViews.findViewById(com.farm.R.id.calendarRight));
        calendarCenter = ((TextView) hasViews.findViewById(com.farm.R.id.calendarCenter));
        rl_time = ((RelativeLayout) hasViews.findViewById(com.farm.R.id.rl_time));
        layout_calendar = ((LinearLayout) hasViews.findViewById(com.farm.R.id.layout_calendar));
        if (rl_time!= null) {
            rl_time.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    TimeSeLectorFragment_.this.rl_time();
                }

            }
            );
        }
        afterOncreate();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<TimeSeLectorFragment_.FragmentBuilder_, com.farm.ui.TimeSeLectorFragment>
    {


        @Override
        public com.farm.ui.TimeSeLectorFragment build() {
            TimeSeLectorFragment_ fragment_ = new TimeSeLectorFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
